name: Build and Test Flexor
on:
  workflow_dispatch:
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup PowerShell
      uses: PSModule/install-powershell@v1

    - name: Build Flexor
      run: |
        ./build.ps1
      shell: pwsh

    - name: Run Tests
      run: |
        dotnet test --verbosity normal --filter "Category!=Integration"
      shell: bash

    - name: Zip Artifacts
      run: |
        zip -r flexor.zip bicepconfig.json .bicep
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: flexor-release
        path: flexor.zip

  add-release-assets:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: flexor-release

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: flexor.zip
